### ISSUE TITLE
Move upload's messaging interface to HTTP endpoints

### ISSUE THREAD

**Issue by rolando-ebi** [HumanCellAtlas/ingest-central#242]
Upload currently sends messages destined for the Ingest Core and Ingest Validator. We should setup HTTP API endpoints instead so that upload doesn't require a direct connection the ingest's RabbitMQ, which we want to lock down

We can either setup an endpoint that wraps a Rabbit message sender, or allow upload to send direct HTTP requests to the APIs wrapping the necessary Core/Validator methods.

**Comment by aaclan-ebi** [comment]
Upload service ticket to adjust to the new endpoints: 
https://app.zenhub.com/workspaces/dcp-backlogs-5ac7bcf9465cb172b77760d9/issues/humancellatlas/upload-service/245

**Comment by aaclan-ebi** [comment]
Target dates for endpoints availability in:
integration: 09/01/2019
staging: 16/01/2019
prod: 23/01/2019

**Comment by aaclan-ebi** [comment]
Change to authenticate requests in messaging endpoints is deployed in dev.

**Comment by aaclan-ebi** [comment]
Summary of changes:

Instead of sending message payload to the the following RabbitMQ queues:
1. exchange: 'ingest.file.staged.exchange'
    queue: 'ingest.file.create.staged'
2. exchange: 'ingest.validation.exchange'
    queue: 'ingest.file.validation.queue'

same message payload must be POSTed to the new HTTP Ingest API endpoints:
1. https://api.ingest.dev.data.humancellatlas.org/messaging/fileUploadInfo
2. https://api.ingest.dev.data.humancellatlas.org/messaging/fileValidationResult

* A self-issued token must be supplied in the request auth header

```curl -v -H 'Content-Type: application/json' -H "Authorization: Bearer $TOKEN"  -X POST https://api.ingest.dev.data.humancellatlas.org/messaging/fileValidationResult -d '{"messageProtocol":null,"documentType":"submissionenvelope","documentId":"5c0fd4a1f37fbd4fdf5ecc51","documentUuid":"22f06985-4313-4837-b2a0-af13dea1d95a","callbackLink":"/submissionEnvelopes/5c0fd4a1f37fbd4fdf5ecc51"}'
```

**Comment by aaclan-ebi** [comment]
This has been pushed to production last week. See https://github.com/HumanCellAtlas/ingest-kube-deployment/blob/master/production/changelog.md#29-january-2019.
