### ISSUE TITLE
Investigate issues with ingest-broker code encountering HTTP connection resets when communicating with the core service.

### ISSUE THREAD

**Issue by justincc** [HumanCellAtlas/ingest-central#282]
This may be causing connection resets and unexpectedly high connection use on ingest core. This ticket encompasses reproducing, logging and fix if necessary.

**Comment by rdgoite** [comment]
Following is a summary of steps taken to investigate this issue:

* Originally suspected that the problem is caused by the Python Requests module or its internal urllib3 module dependency. Added retry logic to code that creates entity in the broker.
* Tested the broker deployed in the local Docker, configured to use Core in the dev Kubernetes cluster. Test spreadsheet (fetal maternal) successfully uploaded (both single and simulateneous multiple submissions). Encountered errors related to local machine going to sleep.
* Deployed and tested broker in the dev Kubernetes cluster. Tests failed with connection reset by peer error.
* Set the broker deployed in dev to access Core (service) using its external domain name; tests succeeded (both single and simultaneous multiple submissions).
* Reconfigured broker deployment to use `ClusterFirst` DNS setting to enable Kubernetes internal domain name resolution.
* Tested spreadsheet upload with several `INGEST_API` settings (all failed with same connection reset by peer error):
  * Service-related environment variables
  * Service name configuration (`ingest-core-service`)
  * Fully qualified service name configuration (e.g. `ingest-core-service.dev-environment.svc.cluster.local`)

This issue is very likely due to the internal Kubernetes cluster networking. However, as the tooling to dig deeper into this issue is yet to be set up, the recommendation for now is to use the domain name configuration and do some testing.

**Comment by dolphyvn** [comment]
Did you try to simulate the error by connecting directly to the pod ip instead of service name? If not, it worth a shot. Btw, would you able to provide some logs?

**Comment by rdgoite** [comment]
No we haven't tried using the pod IP directly. We'll test when we get the chance.

**Comment by rdgoite** [comment]
As for the logs, we currently don't have records of them ready, but we should be able to reproduce the issue and share the logs with you. We'll be sure to update you when they're available.
