### ISSUE TITLE
Dedicated thread for small(er) validation jobs

### ISSUE THREAD

**Issue by zperova** [HumanCellAtlas/ingest-central#291]
This enhancement doesn't relate to the current plan phase (GA) but would be great to have sooner rather than later.

1. What problem does the suggested enhancement solve? Please describe.

I don't want other concurrent submissions to interfere with the speed of processing of my submission.

2. What type of enhancement is this?

Performance, reliability, functionality

3. How much benefit do you estimate this enhancement will provide? (High, Medium, Low)

High

4. Please describe a solution

According to my understanding, all the validation events are randomly assigned to worker threads. It would be great to have a mechanism of having a reserved thread(s) for "ongoing" smaller jobs - such that in case of having a large job take up most of the threads, there is still an opportunity to have smaller jobs run and finish in parallel rather than having them queued after the large job.

**Comment by justincc** [comment]
Could you raise this for discussion in Slack please? Thanks!

**Comment by prabh-t** [comment]
Validator handles file/metadata validation requests concurrently by default. Data file validation requests are sent to Upload, not sure how this is queued and processed at their end, need to check?

**Comment by zperova** [comment]
@prabh-t so this needs to be discussed with Upload service first?

**Comment by justincc** [comment]
I think we'll need a big discussion sooner or later about what we can concurrently put through the system. This is a fundamental architectural issue so I don't think we could make any progress on this until then.

**Comment by zperova** [comment]
@justincc who is the right person to initiate this discussion? once we start ingesting imaging data this will become very relevant for system's reliability due to a number of raw data files in imaging datasets.

**Comment by justincc** [comment]
I'm afraid the approach of this issue isn't correct, since it proposes a specific technical solution which might not be a suitable approach to the use case. Could you edit it (or create a new one) which says what the use case(s) are, perhaps "A small ingestion job of x size takes y long when the system is ingesting another large submission, whereas usually it takes z long. <y> long is too long because of <this-good-reason>? Then please could you highlight this to @morrisonnorman to ask development to consider and prioritize against other stuff. Managing load better it's definitely something we need but even just consideration and design will take a long time since this is a complex issue, hence has to be balanced against other priorities.
