### ISSUE TITLE
JSON metadata generated by ingest does not contain schema_version field

### ISSUE THREAD

**Issue by daniwelter** [HumanCellAtlas/ingest-central#298]
Steps to reproduce the behaviour:
1. Go to http://api.ingest.data.humancellatlas.org
2. Go to any metadata entity, eg http://api.ingest.data.humancellatlas.org/biomaterials/5c48411b1603f500078b4c3d
3. Observe the absence of 'schema_version' from the json

I expect the version number of the schema to be present in all JSON documents as it is needed for a number of data operations such as migrating data from schema version to schema version. While it is possible to regex the schema version out of the described_by field, this is undesirable as it is more error prone than accessing a version field directly.

**Comment by maniarathi** [comment]
The metadata schema integration test work will require the schema_version to be populated in addition to its current population in described_by due to the fact that downstream components will be required to specify metadata versions that they are compatible with and parsing a range based on a URL is not supported.

This is currently blocked by an effort to establish how to specify the schema_version due to the fact that ElasticSearch is not enabled to search a range of semantic versions (i.e. 3.4.5 -> 5.3.0 is meaningless; only integers or floats are acceptable).

**Comment by justincc** [comment]
It might be good for ingest to parse the `describedBy` and fill in schema version (or future major/minor according to [Arathi's proposal](https://docs.google.com/document/d/1BInKossmrlpna5MV_s4MSR0Bll1wnD-3OVw-9nCLdWg/edit#heading=h.oi3irvfr3niv)). Then we don't have the danger of inconsistency between `describedBy` and these fields, though it does lock us in to a certain format of `describedBy`.

**Comment by maniarathi** [comment]
This is now tracked by a ticket in ingest-client as the population of the provenance properties are done via code in ingest-client (https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/ingest-client/44)
