### ISSUE TITLE
[UI] Recent submissions don't show up on submission dashboard

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/ingest-central#437]
**To Reproduce**

1. Go to UI in dev
1. Upload a spreadsheet
1. Don't see submission in UI
1. Click "eye" to view all - see submission

**Expected behaviour**

Please explain what you expected to happen.
    
I expect that my submissions show up in the submission dashboard.

**Actual behaviour**

My new submissions don't show up in the submission dashboard.

**Impact**

User won't easily be able to view their own submissions. They will have to click "show all" (eye icon) to view all submission.

**Screenshots or Messages**

What I see now (no submission since May 1):
![Screen Shot 2019-06-12 at 12 26 02](https://user-images.githubusercontent.com/10993501/59347902-af7ff280-8d0d-11e9-9c72-70aa14cc1b30.png)

What I see when I view all (red circled submission are mine): 
![Screen Shot 2019-06-12 at 12 26 19](https://user-images.githubusercontent.com/10993501/59347970-da6a4680-8d0d-11e9-8332-abc2e2a4d599.png)

**Comment by aaclan-ebi** [comment]
Dev notes: The issue started happening when we disabled authentication for requests which are coming from internal components. When the user gets authenticated in the UI, the token of the user is should be used in the headers for the request to create a submission. Since authentication was disabled, the user info which is coming from the token is not being stored. I've put that authentication back and the submissions should now have user info. The UI should be able to query the submissions for the specific user.


@malloryfreeberg , the fix is now deployed in dev.

**Comment by aaclan-ebi** [comment]
Fix is in integration now, will be deployed to staging later today and to prod next week.
