### ISSUE TITLE
On request give the user the last successfully submitted spreadsheet for a submission.

### ISSUE THREAD

**Issue by justincc** [HumanCellAtlas/ingest-central#460]
From conversation with @rolando-ebi it sounds like after an update we would still give them back the original submission spreadsheet instead of the updated one which contains the last changes.

**Acceptance criteria**
When the user requests a spreadsheet to update a submission they always get the latest one successfully submitted.

**Comment by justincc** [comment]
This does not include tracking which update submission actually got submitted. This will be a known limitation since we will very likely replace this approach with spreadsheet generation.

**Comment by brianraymor** [comment]
Added Milestone and Release per discussion on the August 1 Refinement call.

**Comment by rdgoite** [comment]
This ticket turns out to be more complex than originally thought. Keeping track of the spreadsheet data through the submission UUID was not effective as UUIDs are generated for each new submission, and submissions are loosely related. The most sensible option for us seems to be to keep track of spreadsheet submissions through the project UUID as the project is what we can consider to be the common thing among all submissions that pertain to the same dataset. 

However, getting hold of the project UUID for the very first submission for a given project is a little tricky as the spreadsheet storage occurs in the context of the broker, while the project UUIDs are only assigned in the Core once the metadata is recorded. To be able to keep track of spreadsheet data based on the project UUID, we will need to update the code to store the spreadsheet only after the information is available.

**Comment by justincc** [comment]
After discussion with @rdgoite we will not complete implementation a) because of the unanticipated complexity and b) because we know the approach has to change anyway to one where we regenerated spreadsheets, which is itself a high complexity task. Instead, we will document a workaround for the wranglers.
