### ISSUE TITLE
Make the updated file versions in the datastore consistent with Ingest's record of these versions

### ISSUE THREAD

**Issue by justincc** [HumanCellAtlas/ingest-central#472]
**Acceptance criteria**
The datastore file versions and ingest's DCP version are the same.

**Comment by rdgoite** [comment]
This is actually a false negative. I checked this by querying both the original and the updated bundles from [a recent run of the end-to-end test](https://allspark.dev.data.humancellatlas.org/HumanCellAtlas/dcp/pipelines/13508), and it looks like versions are consistent in both cases. I originally reported this being an issue because the assertions made back then in the end-to-end test were failing.

Note however, that in the previously mentioned test run, 2 bundles were specified in the bundle manifest, one of which being the bundle from the original submission.

**Comment by justincc** [comment]
Does this potential have two components?

1) Adjusting our own records to match what got into the datastore
2) Fixing our code so that the versions we give the datastore are our ones rather than the ones they autogenerate.

**Comment by aaclan-ebi** [comment]
@justincc are there specific records which are reported inconsistent? 

@rdgoite and I checked the 2 bundles in the update submission of the test run, and those are the primary and analysis bundles. This behaviour is expected since the scope of the "simple updates" is that Ingest will update primary and analysis bundles. And no workflows should run for the updated primary bundle.

**Comment by aaclan-ebi** [comment]
no actual cases, reclosing this now (since i reopened it).

**Comment by justincc** [comment]
Why did you reopen again?

**Comment by aaclan-ebi** [comment]
I reopened just in case there are actual cases where there's inconsistency, but based from offline conversation there was none.

**Comment by aaclan-ebi** [comment]
ah i reopened because I don't want to put it in "Done".

**Comment by justincc** [comment]
Buuut, isn't it done?

**Comment by aaclan-ebi** [comment]
yes but it was Closed prior to that. I didn't want to close it yet, I believe you wanted tickets to be put to Done first.

**Comment by aaclan-ebi** [comment]
sorry for the confusion, i corrected my wording to:

ah i reopened because I want to put it in "Done".

it was:
ah i reopened because I dont want to put it in "Done".
