### ISSUE TITLE
128 bundles failed for Mouse Gastrulation Atlas

### ISSUE THREAD

**Issue by ESapenaVentura** [HumanCellAtlas/ingest-central#499]
For Mouse gastrulation atlas, 128 bundles never got to see the sunlight:

- __Submission UUID__: a32f53ce-d752-47a0-8372-d15d17e5f645
- __When__: 08/08/2019
- __Ticket in Wrangling repo__: [Here](https://github.com/HumanCellAtlas/hca-data-wrangling/issues/208)

**Comment by rdgoite** [comment]
If I understand correctly, for this dataset, there are 63 donors, and some of the specimens in this dataset refer to multiple donors. Upon initial investigation, the 128 bundles seem to have gone missing due to a problem between Ingest and upload service during the upload of the metadata for one of the donors (`346bf1a8-319c-4bc9-88d2-c27b6eaf8240`). Here's a link to the [logs I've gathered through Kibana](https://drive.google.com/open?id=1daUmvBnyipKCLEGERGPRMzaLRGLFNK1F).

**Comment by parthshahva** [comment]
This is the known issue that occured for Tabula Muris. This is due to the simultaneous upload of the same metadata file that will be resolved in the exporter redesign.

fixed the files (['a32f53ce-d752-47a0-8372-d15d17e5f645/donor_organism_346bf1a8-319c-4bc9-88d2-c27b6eaf8240.json', 'a32f53ce-d752-47a0-8372-d15d17e5f645/process_483152cb-8df6-4636-b859-9be354182f34.json']) so that exporting can be finished

**Comment by ESapenaVentura** [comment]
I've looked at it in the tracker and it seems that it still isn't finished uploading :/ Any idea?

**Comment by parthshahva** [comment]
@ESapenaVentura I just fixed the files. An ingest developer still needs to kick the exporting

**Comment by ESapenaVentura** [comment]
Thanks @parthshahva ! I've talked with @rdgoite today and we will work on this next week. We are prioritising the other dataset as we need it uploaded ASAP

**Comment by justincc** [comment]
We will pause this at least until next ingest sprint (beginning 2019-08-20) in favor of addressing #482

**Comment by justincc** [comment]
Had a word with @ESapenaVentura and he says he is prioritizing Barcelona datasets first. He will come back to this when he is ready.

**Comment by justincc** [comment]
@ESapenaVentura this is no longer blocked now we have the exporter fixes. However, please could you ping us when you proceed.

**Comment by ESapenaVentura** [comment]
What would be the next step? Re-submit?

**Comment by justincc** [comment]
Good question. @rdgoite?

**Comment by jlzamanian** [comment]
@dataops

**Comment by justincc** [comment]
@ESapenaVentura please re-submit
