### ISSUE TITLE
2ry Analysis envelope stuck (Spatio-temporal immune...kidney)

### ISSUE THREAD

**Issue by jahilton** [HumanCellAtlas/ingest-central#527]
2ry Analysis workflow completed successfully on Aug 22nd
https://job-manager.caas-prod.broadinstitute.org/jobs/b69f261e-f450-4af1-bf76-7f2b982df01d

The corresponding submissionEnvelope `submissionState` is still `Submitted`
https://api.ingest.data.humancellatlas.org/submissionEnvelopes/5d5ede1597ecaa0008d3dc78

**Comment by jahilton** [comment]
@justincc What are my next steps to resolve this issue?

**Comment by justincc** [comment]
Hey @jahilton. I assigned you as the contact point outside ingest (this isn't always the creator). Tomorrow (Wed) somebody in ingest dev will pick this up and we'll let you know where the problem is. If it's in ingest we'll address it.

**Comment by rolando-ebi** [comment]
Ingest-core restarted for an unknown reason during the processing of this analysis submission. Since the work queue for processing analysis submissions is stored in memory, the work wasn't continued when the ingest-core restarted. As part of reliability efforts we should ensure that the work queue for processing submissions is durable and can be resumed after ingest-core failures

I've re-submitted this analysis submission and we should see bundles for it shortly

**Comment by jahilton** [comment]
Looks like the submission Envelope has been 'Processing' for >24 hrs. Is this expected?

**Comment by aaclan-ebi** [comment]
Hi @jahilton , it looks like it encountered another issue after the submission was resubmitted around 11am, 4th Sep (https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/ingest-central/482)  The fix was deployed to prod later that day, 6pm. We've retried the exporting now and it went successful. Apologies for the delay in getting the analysis bundle to production.
