### ISSUE TITLE
Fix internal integration tests

### ISSUE THREAD

**Issue by justincc** [HumanCellAtlas/ingest-central#531]
See https://allspark.dev.data.humancellatlas.org/HumanCellAtlas/ingest-integration-tests/-/jobs/44719

**Comment by aaclan-ebi** [comment]
The update test in the internal integration tests was failing because the update submission envelope gets stuck in Submitted. The code which search the bundles to be updated seems broken but no log was found. Upon investigation with @MightyAx . we found out that there's a bundle manifest manually created in staging and some fields were not populated. https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/ingest-central/491 
This breaks that code and no bundles are being processed. 

Tasks done:
- Fixed the code to handle the data
- Added try catch in the thread so that it'll log any exceptions

@MightyAx pushed the ff changes:
https://github.com/HumanCellAtlas/ingest-core/compare/4201d325fa55...13f4a6efbba7

Gonna deploy this to dev and integration today and this should reach staging next week.

Test should pass by then. :-)

**Comment by justincc** [comment]
Great, good work guys :)
