### ISSUE TITLE
When adding meta/data allow spreadsheets to refer both to new and existing entities

### ISSUE THREAD

**Issue by justincc** [HumanCellAtlas/ingest-central#533]
As discussed in the internal demo on 2019-09-03. Ask Marion.

**Comment by MightyAx** [comment]
Spreadsheets for existing data include UIDs, Spreadsheets for new data do not.
When updating and adding at the same time, currently multiple spreadsheets are required.

**Comment by aaclan-ebi** [comment]
Steps to Reproduce:
1. Upload the spreadsheet which have some uuid columns populated, some are not.

Actual Behavior:
1. Would give the submission error:
`500 Server Error: for url: http://172.20.105.197:80/protocols/search/findByUuid?uuid=`

Expected behavior:
2. Successful linking to previous and entities in the spreadsheet.
[https://app.zenhub.com/files/132741306/3b7cc4a7-54cb-4629-aec7-24bfa8694fc5/download](https://app.zenhub.com/files/132741306/3b7cc4a7-54cb-4629-aec7-24bfa8694fc5/download)
Original spreadsheet from Marion: 


Fixed spreadsheet file (Removed id columns for those with uuid link columns): [https://app.zenhub.com/files/132741306/d8015491-b645-4855-a6e9-2f4bfb29e1f3/download](https://app.zenhub.com/files/132741306/d8015491-b645-4855-a6e9-2f4bfb29e1f3/download)

**Comment by aaclan-ebi** [comment]
The fixed spreadsheet should be now possible to upload with correct linking. @mshadbolt I'm going to cleanup all added submissions to this `Ischaemic sensitivity of human tissue by single cell RNA seq` in staging. Could you try inspect the fixed spreadsheet file mentioned above and verify that entities are linked correctly?

**Comment by aaclan-ebi** [comment]
Please note that the fix will be released to staging on wed, this week.

**Comment by mshadbolt** [comment]
I am kind of confused about what you want me to do for this? I thought we were reingesting everything with new and old data as a batch rather than fixing the old submission, or is this just testing some sort of functionality. 

Also why is there a row that is highlighted?

**Comment by aaclan-ebi** [comment]
Sorry for the confusion. Yes, we're going to do the reingestion approach for this dataset.

Just want to let you know that it should be possible to upload new data using only one spreadsheet. It should be possible to link entities to both new (entities in the spreadsheet) and existing entities in Ingest.

I just realised that there's still a change in the exporter needed to be able to submit this. The backwards compatibility issue with schema version fields --- that's not fixed yet. We're still resolving the other issues discussed last time.

**Comment by aaclan-ebi** [comment]
I think that row was causing the error and i was debugging the issue and highlighted the row for me to remember. Please disregard the red highlight, i just forgot to remove it. 

I also think that it would be good for you guys to see the actual linking in the UI, I'm not sure how to present that in the UI, I will probably consult Gabs, what's the best way to do this.
But it's possible to see the links thru the API for now.

**Comment by mshadbolt** [comment]
So this being closed means you don't want me to do anything?

**Comment by justincc** [comment]
Correct. We'll test this out on some other project when we have other bits of adding new bundles in place.
