### ISSUE TITLE
Missing 2 bundles from the Gary Bader dataset in Staging.

### ISSUE THREAD

**Issue by willrockout** [HumanCellAtlas/ingest-central#559]
For the SingleCellLiverLandscape (Gary Bader) dataset, I tested export in staging and two bundles gave errors:
<img width="1390" alt="Screen Shot 2019-09-16 at 11 28 23 AM" src="https://user-images.githubusercontent.com/19597324/64983356-2b418c00-d875-11e9-9310-312b3ffe1161.png">

- Submission id: 5d7fc4fbe397b20008ae91a2
- When: 9/16/19

**Comment by rdgoite** [comment]
It looks like the problem was caused by the exporter exhausting attempts before the cloud URL was ready. To address this, we can do the following:

* Adjust the re-attempt configuration for exporter so they wait for a bit longer.
(Would be nice to know how long they waited for, and when the staging of the file was done, but we don't have this information readily available.)

Longer term modifications:

* Allow the user to re-submit a failed bundle, or have a system that does this automatically.
  * Capture all the failed attempts and have another process manage them.
* Improve logging for the new exporter code.
  * Keep track of staging details especially when exceptions are raised.
    * This ties in with [distributed tracing instrumentation](https://app.zenhub.com/workspace/o/humancellatlas/ingest-central/issues/433).

**Comment by rdgoite** [comment]
@willrockout I have re-triggered the export for the bundles that failed. The submission is now complete.

In the meantime, I have updated the exporter deployment in staging to wait longer for upload data to be ready; this should help prevent this issue in the future. In case we encounter this again, we can reconfigure. Please refer to my previous comment for some of the other longer term things we can do.

**Comment by jlzamanian** [comment]
@HumanCellAtlas/data-ops
