### ISSUE TITLE
[schema] organism_age_unit text field uses both year/years and month/months, etc.

### ISSUE THREAD

**Issue by theathorn** [HumanCellAtlas/ingest-central#56]
**To Reproduce**

In biomaterials.json within `biomaterials[*]."content.organism_age_unit.text` the filed value in the Preview Data sets uses both "year" and "years" and "month" and "months" for the age unit.

**Expected behaviour**

A single term should be used/enforced for each type of unit (e.g. "year" not "years").
    

**Actual behaviour**

Multiple text terms are used for the same age unit (e.g. year/years, month/months, week/weeks, day/days).

**Impact**

The Data Browser will index "year" and "years" separately and the UI will render them as separate entities when obviously they are the same.

**Comment by danielvaughan** [comment]
This looks like a metadata schema ticket.

**Comment by malloryfreeberg** [comment]
This field is now governed by an ontology, and all the time units in the ontology are singular. We didn't have ontology validation turned on for the preview release, which would have caught this error. Since we need to re-ingest these datasets anyway for the pilot, the units will be standardised (I believe ontology validation will be working for the pilot).

**Comment by theathorn** [comment]
OK, I think we can close this then.
