### ISSUE TITLE
[UI] HttpErrorResponse while uploading spreadsheet

### ISSUE THREAD

**Issue by cjvillar** [HumanCellAtlas/ingest-central#57]
I tried to upload a file at http://ui.ingest.dev.data.humancellatlas.org/submissions/new/metadata but received a vague error:

"HttpErrorResponse: Http failure response for http://ingest.dev.data.humancellatlas.org/api_upload: 400 BAD REQUEST"

I'm not sure what this means.

**Comment by malloryfreeberg** [comment]
See also Issue #44

**Comment by rdgoite** [comment]
I looked into this issue yesterday and found out that the spreadsheet in question is causing an error in the Importer for having multiple Projects defined. This is caused by phantom entries in the Project worksheet that aren't visible when looking at it from Excel. Normally, deleting all rows after the last visible entry will address this issue. However, if that still doesn't work, the next thing is to move all visible entries to a fresh worksheet.

However, it should be noted that the Importer should not really complain about multiple Projects defined in a spreadsheet. Also, it would have been more useful for Data Wranglers if the Importer actually told them about the problem of having multiple Projects instead of just "HttpErrorResponse" message, which is pretty confusing.

**Comment by aaclan-ebi** [comment]
Fix to phantom entries is currently deployed in dev. Please try uploading the spreadsheet again and let us know if the issue still persists.
