### ISSUE TITLE
Simple AUDR to Spatio-temporal immune zonation of the human kidney.

### ISSUE THREAD

**Issue by willrockout** [HumanCellAtlas/ingest-central#576]
I'm going to change the incorrect species ontology from homo sapiens to Homo sapiens.

This will be done on 9/25/19 with the following submission id 5d51692a1a249400085ac36a.

I will upload the spreadsheet to the correct brokering folder for future AUDR's.

**Comment by justincc** [comment]
Production ingest is currently falling over when we try to handle this. We need to find out why and fix. Firstly, we need to find out whether this is related to this submission or a more general failure caused by other factors (e.g. [Parth's runaway Cron script](https://humancellatlas.slack.com/archives/C9ENBPVNW/p1569516916035800?thread_ts=1569516795.035600&cid=C9ENBPVNW)).

**Comment by justincc** [comment]
We believe now that the problem is probably confined to AUDR of this dataset and not generic. We're continuing to investigate. Please don't attempt to AUDR this dataset again until we give the all clear.

**Comment by justincc** [comment]
@willrockout is this a Barcelona dataset?

**Comment by mshadbolt** [comment]
Yes this is CZI incentive dataset

**Comment by jlzamanian** [comment]
@HumanCellAtlas/data-ops

**Comment by rolando-ebi** [comment]
The fix for the slow read API call is in production. We should be able to re-trigger the update request now

**Comment by aaclan-ebi** [comment]
Update submission is now Complete. 94 bundles were updated https://ui.ingest.data.humancellatlas.org/submissions/detail/5d8b986fbddf5d0008110b3e/overview

@willrockout please verify if the updates were picked up by the data browser. Thanks!
