### ISSUE TITLE
Address non-production backups not running

### ISSUE THREAD

**Issue by justincc** [HumanCellAtlas/ingest-central#614]
As of 2019-11-08 we found out these weren't running.

**Acceptance criteria**
* Answer why we weren't alerted that these weren't running. DONE (see below)
* Make sure they are running.  DONE
* Enhance config/scripts so that backup and verification jobs are set up at the same time as Mongo
* Add a step in the backup SOP to manually check these jobs have been setup.
* Make sure this information is reflected in the backup documentation

**Comment by rdgoite** [comment]
This was due to the whole backup mechanism not being deployed. Backup and verification jobs are deployed together. What we can do here is to add the backup and verification job setup to the same infrastructure script that sets up MongoDB itself, so that we can ensure that the database is always deployed with the backup scripts.
